package modelo;
// Generated 13/03/2018 03:47:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private int idempresa;
     private String nombre;
     private String oficinas;
     private Integer numeroempleados;
     private String contacto;
     private String presidente;
     private Set vacantes = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(int idempresa) {
        this.idempresa = idempresa;
    }
    public Empresa(int idempresa, String nombre, String oficinas, 
            Integer numeroempleados, String contacto, String presidente, 
            Set vacantes) {
       this.idempresa = idempresa;
       this.nombre = nombre;
       this.oficinas = oficinas;
       this.numeroempleados = numeroempleados;
       this.contacto = contacto;
       this.presidente = presidente;
       this.vacantes = vacantes;
    }
   
    public int getIdempresa() {
        return this.idempresa;
    }
    
    public void setIdempresa(int idempresa) {
        this.idempresa = idempresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getOficinas() {
        return this.oficinas;
    }
    
    public void setOficinas(String oficinas) {
        this.oficinas = oficinas;
    }
    public Integer getNumeroempleados() {
        return this.numeroempleados;
    }
    
    public void setNumeroempleados(Integer numeroempleados) {
        this.numeroempleados = numeroempleados;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getPresidente() {
        return this.presidente;
    }
    
    public void setPresidente(String presidente) {
        this.presidente = presidente;
    }
    public Set getVacantes() {
        return this.vacantes;
    }
    
    public void setVacantes(Set vacantes) {
        this.vacantes = vacantes;
    }




}


