package modelo;
// Generated 13/03/2018 03:47:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Experiencialaboral generated by hbm2java
 */
public class Experiencialaboral  implements java.io.Serializable {


     private int idexperiencia;
     private Profesionista profesionista;
     private String empresa;
     private String cargo;
     private Date periodo;

    public Experiencialaboral() {
    }

	
    public Experiencialaboral(int idexperiencia) {
        this.idexperiencia = idexperiencia;
    }
    public Experiencialaboral(int idexperiencia, Profesionista profesionista, String empresa, String cargo, Date periodo) {
       this.idexperiencia = idexperiencia;
       this.profesionista = profesionista;
       this.empresa = empresa;
       this.cargo = cargo;
       this.periodo = periodo;
    }
   
    public int getIdexperiencia() {
        return this.idexperiencia;
    }
    
    public void setIdexperiencia(int idexperiencia) {
        this.idexperiencia = idexperiencia;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Date getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Date periodo) {
        this.periodo = periodo;
    }




}


