package modelo;
// Generated 13/03/2018 03:47:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Formacion generated by hbm2java
 */
public class Formacion  implements java.io.Serializable {


     private int idformacion;
     private Profesionista profesionista;
     private String colegio;
     private Integer grado;
     private Date periodo;

    public Formacion() {
    }

	
    public Formacion(int idformacion) {
        this.idformacion = idformacion;
    }
    public Formacion(int idformacion, Profesionista profesionista, String colegio, Integer grado, Date periodo) {
       this.idformacion = idformacion;
       this.profesionista = profesionista;
       this.colegio = colegio;
       this.grado = grado;
       this.periodo = periodo;
    }
   
    public int getIdformacion() {
        return this.idformacion;
    }
    
    public void setIdformacion(int idformacion) {
        this.idformacion = idformacion;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }
    public String getColegio() {
        return this.colegio;
    }
    
    public void setColegio(String colegio) {
        this.colegio = colegio;
    }
    public Integer getGrado() {
        return this.grado;
    }
    
    public void setGrado(Integer grado) {
        this.grado = grado;
    }
    public Date getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Date periodo) {
        this.periodo = periodo;
    }




}


