package modelo;
// Generated 13/03/2018 03:47:13 PM by Hibernate Tools 4.3.1



/**
 * Postular generated by hbm2java
 */
public class Postular  implements java.io.Serializable {


     private int idpostular;
     private Profesionista profesionista;
     private Vacante vacante;
     private Boolean aceptado;

    public Postular() {
    }

	
    public Postular(int idpostular) {
        this.idpostular = idpostular;
    }
    public Postular(int idpostular, Profesionista profesionista, Vacante vacante, Boolean aceptado) {
       this.idpostular = idpostular;
       this.profesionista = profesionista;
       this.vacante = vacante;
       this.aceptado = aceptado;
    }
   
    public int getIdpostular() {
        return this.idpostular;
    }
    
    public void setIdpostular(int idpostular) {
        this.idpostular = idpostular;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }
    public Vacante getVacante() {
        return this.vacante;
    }
    
    public void setVacante(Vacante vacante) {
        this.vacante = vacante;
    }
    public Boolean getAceptado() {
        return this.aceptado;
    }
    
    public void setAceptado(Boolean aceptado) {
        this.aceptado = aceptado;
    }




}


