package modelo;
// Generated 13/03/2018 03:47:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesionista generated by hbm2java
 */
public class Profesionista  implements java.io.Serializable {


     private int idprofesionista;
     private String nombre;
     private String apellidopaterno;
     private String nacionalidad;
     private String carrera;
     private String telefono;
     private String contrasena;
     private Set postulars = new HashSet(0);
     private Set skils = new HashSet(0);
     private Set formacions = new HashSet(0);
     private Set experiencialaborals = new HashSet(0);

    public Profesionista() {
    }

	
    public Profesionista(int idprofesionista, String nombre, String apellidopaterno, String nacionalidad, String carrera, String telefono, String contrasena) {
        this.idprofesionista = idprofesionista;
        this.nombre = nombre;
        this.apellidopaterno = apellidopaterno;
        this.nacionalidad = nacionalidad;
        this.carrera = carrera;
        this.telefono = telefono;
        this.contrasena = contrasena;
    }
    public Profesionista(int idprofesionista, String nombre, String apellidopaterno, String nacionalidad, String carrera, String telefono, String contrasena, Set postulars, Set skils, Set formacions, Set experiencialaborals) {
       this.idprofesionista = idprofesionista;
       this.nombre = nombre;
       this.apellidopaterno = apellidopaterno;
       this.nacionalidad = nacionalidad;
       this.carrera = carrera;
       this.telefono = telefono;
       this.contrasena = contrasena;
       this.postulars = postulars;
       this.skils = skils;
       this.formacions = formacions;
       this.experiencialaborals = experiencialaborals;
    }
   
    public int getIdprofesionista() {
        return this.idprofesionista;
    }
    
    public void setIdprofesionista(int idprofesionista) {
        this.idprofesionista = idprofesionista;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidopaterno() {
        return this.apellidopaterno;
    }
    
    public void setApellidopaterno(String apellidopaterno) {
        this.apellidopaterno = apellidopaterno;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set getPostulars() {
        return this.postulars;
    }
    
    public void setPostulars(Set postulars) {
        this.postulars = postulars;
    }
    public Set getSkils() {
        return this.skils;
    }
    
    public void setSkils(Set skils) {
        this.skils = skils;
    }
    public Set getFormacions() {
        return this.formacions;
    }
    
    public void setFormacions(Set formacions) {
        this.formacions = formacions;
    }
    public Set getExperiencialaborals() {
        return this.experiencialaborals;
    }
    
    public void setExperiencialaborals(Set experiencialaborals) {
        this.experiencialaborals = experiencialaborals;
    }




}


