package modelo;
// Generated 13/03/2018 03:47:13 PM by Hibernate Tools 4.3.1



/**
 * Skil generated by hbm2java
 */
public class Skil  implements java.io.Serializable {


     private int idskil;
     private Profesionista profesionista;
     private String nombre;
     private Integer grado;

    public Skil() {
    }

	
    public Skil(int idskil) {
        this.idskil = idskil;
    }
    public Skil(int idskil, Profesionista profesionista, String nombre, Integer grado) {
       this.idskil = idskil;
       this.profesionista = profesionista;
       this.nombre = nombre;
       this.grado = grado;
    }
   
    public int getIdskil() {
        return this.idskil;
    }
    
    public void setIdskil(int idskil) {
        this.idskil = idskil;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getGrado() {
        return this.grado;
    }
    
    public void setGrado(Integer grado) {
        this.grado = grado;
    }




}


