package modelo;
// Generated 13/03/2018 03:47:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vacante generated by hbm2java
 */
public class Vacante  implements java.io.Serializable {


     private int idvacante;
     private Empresa empresa;
     private String puesto;
     private String lugar;
     private Integer salario;
     private String horario;
     private String descripcion;
     private String actividades;
     private Set postulars = new HashSet(0);

    public Vacante() {
    }

	
    public Vacante(int idvacante) {
        this.idvacante = idvacante;
    }
    public Vacante(int idvacante, Empresa empresa, String puesto, String lugar, Integer salario, String horario, String descripcion, String actividades, Set postulars) {
       this.idvacante = idvacante;
       this.empresa = empresa;
       this.puesto = puesto;
       this.lugar = lugar;
       this.salario = salario;
       this.horario = horario;
       this.descripcion = descripcion;
       this.actividades = actividades;
       this.postulars = postulars;
    }
   
    public int getIdvacante() {
        return this.idvacante;
    }
    
    public void setIdvacante(int idvacante) {
        this.idvacante = idvacante;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Integer getSalario() {
        return this.salario;
    }
    
    public void setSalario(Integer salario) {
        this.salario = salario;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getActividades() {
        return this.actividades;
    }
    
    public void setActividades(String actividades) {
        this.actividades = actividades;
    }
    public Set getPostulars() {
        return this.postulars;
    }
    
    public void setPostulars(Set postulars) {
        this.postulars = postulars;
    }




}


